<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Ajax</title>
    </head>
    <body>
        <main>
            <button id="loadStudents">Load Students</button>
            <div data-js-students></div>
        </main>
        <script src='/js/main.js'></script>
    </body>
</html>
